<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
    <dict>
        <key>scopeName</key>
        <string>bmcode.log</string>
        <key>fileTypes</key>
        <array>
            <string>log</string>
        </array>
        <key>name</key>
        <string>Log file</string>
        <key>patterns</key>
        <array>
            <dict>
                <key>match</key>
                <string>[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}</string>
                <key>name</key>
                <string>info-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(hint|info[\\:]?|information))\b</string>
                <key>name</key>
                <string>info-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(warning|warn?|test))\b</string>
                <key>name</key>
                <string>warn-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(Down|Error|Failure|Fail|Fatal))\b</string>
                <key>name</key>
                <string>error-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>"([^\\\"]+|\\.)*"|'([^\\\']+|\\.)*'</string>
                <key>name</key>
                <string>token.string</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f|ll|LL|ull|ULL)?\b</string>
                <key>name</key>
                <string>constant.numeric</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(local))\b</string>
                <key>name</key>
                <string>info-token</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\b(?i:(server|running))\b</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
            <dict>
                <key>match</key>
                <string>(-)+>|├(─)+</string>
                <key>name</key>
                <string>comment.line</string>
            </dict>
            <dict>
                <key>match</key>
                <string>\S+@\S+\.\S+</string>
                <key>name</key>
                <string>info-token</string>
            </dict>
        </array>
        <key>uuid</key>
        <string>ab259404-3072-4cd4-a943-7cbbd32e373f</string>
    </dict>
</plist>